name: Chess Bot
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  move:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: pip install chess PyGithub
        
      - name: Run Chess Engine
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py
